### PR TITLE
News page

### PR DESCRIPTION
**Pull request by wakaflorien**
### What does this PR do?

- adds news page with pagination.
- adds language translation.

### How to test it?

- checkout to `news-page` branch then run `npm start`

### ** Screenshots**
Screenshot from 2022-08-16 09-29-05
Screenshot from 2022-08-16 09-36-46
Screenshot from 2022-08-16 09-36-49
Screenshot from 2022-09-09 14-45-59

### CODE REVIEW

**Review by jeandamascyifuzo — COMMENTED** [review]
plz add a screenshot 4 ur work

**Comment by jeandamascyifuzo** [comment]
u've to create another page for reading more details

**Comment by jeandamascyifuzo** [comment]
plz rebase and add translation to ur work

**Comment by wakaflorien** [comment]
> plz rebase and add translation to ur work

on it.

**Comment by wakaflorien** [comment]
all reviews are completed.

**Review by jeandamascyifuzo — APPROVED** [review]

**Pull request merged**
